name: tlslite
version: 1.0.0
description: A Dart implementation of the TLS protocol.

environment:
  sdk: '^3.6.0'

dependencies:
  ffi: ^2.1.2
  meta: ^1.15.0
  logging: ^1.3.0
  pointycastle: ^4.0.0
  fixnum: ^1.1.1
  collection: ^1.18.0
  convert: ^3.1.2

dev_dependencies:   
  hex: ^0.2.0
  test: ^1.26.3  
  ffigen: ^19.0.0
  benchmark_harness: ^2.3.1
 