name: tlslite
version: 1.0.0
description: A Dart implementation of the TLS protocol.

environment:
  sdk: '^3.6.0'

dependencies:
  ffi: ^2.1.2
  meta: ^1.15.0
  convert: any
  pointycastle: ^4.0.0
  crypto: any
  fixnum: ^1.1.1
  collection: ^1.18.0

dev_dependencies:  
  test: any
  hex: any  
  ffigen: ^12.0.0
  benchmark_harness: any
 